/**
 * Tailwind config for the landing page and the Arena/Campaign pre-game
 * screens, so they all share the same "PARAGON" design language. The rest
 * of the app (live gameplay HUD/canvas) uses its own hand-written CSS (see
 * app/globals.css) and never imports landing.css.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/page.tsx",
    "./app/landing.css",
    "./components/BackToHome.tsx",
    "./components/ArenaClient.tsx",
    "./components/AdventureClient.tsx",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#00d2ff",
        primary: "#a5e7ff",
        "surface-dim": "#131315",
        "primary-fixed-dim": "#47d6ff",
        "on-primary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#584400",
        "on-secondary-fixed": "#241a00",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#23005b",
        "on-surface": "#e5e1e4",
        "inverse-surface": "#e5e1e4",
        "surface-bright": "#39393b",
        outline: "#859399",
        "surface-variant": "#353437",
        "surface-tint": "#47d6ff",
        "outline-variant": "#3c494e",
        "on-primary": "#003543",
        "surface-container-highest": "#353437",
        "ethereal-purple": "#7000ff",
        background: "#131315",
        "surface-container-high": "#2a2a2c",
        "primary-fixed": "#b6ebff",
        "on-primary-container": "#00566a",
        "paragon-gold": "#ffcc00",
        tertiary: "#e5d7ff",
        "on-tertiary-fixed-variant": "#5700c9",
        secondary: "#ffecc0",
        "on-error": "#690005",
        "tertiary-fixed": "#e9ddff",
        "on-tertiary": "#3c0090",
        "error-container": "#93000a",
        "tertiary-container": "#ccb6ff",
        "tertiary-fixed-dim": "#d1bcff",
        "on-primary-fixed-variant": "#004e60",
        "surface-container-low": "#1c1b1d",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e1e4",
        "on-secondary": "#3d2f00",
        "on-tertiary-container": "#6100de",
        "on-secondary-container": "#6e5700",
        "surface-container": "#201f21",
        "inverse-primary": "#00677f",
        "secondary-container": "#fecb00",
        "void-black": "#0a0a0c",
        "surface-container-lowest": "#0e0e10",
        "secondary-fixed-dim": "#f1c100",
        "inverse-on-surface": "#313032",
        "secondary-fixed": "#ffe08b",
        "obsidian-grey": "#1a1a1e",
        "on-surface-variant": "#bbc9cf",
        surface: "#131315",
        "mana-glow": "#00d2ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-lg": "64px",
      },
      fontFamily: {
        "display-hero": ["var(--font-epilogue)"],
        "section-label": ["var(--font-jetbrains-mono)"],
        "headline-lg-mobile": ["var(--font-epilogue)"],
        "body-md": ["var(--font-hanken-grotesk)"],
        "headline-lg": ["var(--font-epilogue)"],
        "keycap-label": ["var(--font-jetbrains-mono)"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "section-label": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "700" }],
        "keycap-label": ["12px", { lineHeight: "12px", fontWeight: "600" }],
      },
    },
  },
};
