import {
  ARMOR_BREAK_DURATION,
  KACPER_LMB_CAST,
  KACPER_RMB_CAST,
  KACPER_ULT_COOLDOWN,
  KACPER_ULT_COST,
  KACPER_ULT_DURATION,
  rangeFor,
  PARAGON_DASH_COOLDOWN,
  PARAGON_DASH_TIME,
  PARAGON_LMB_CAST,
  PARAGON_RMB_CAST,
  REFLECT_COOLDOWN,
  REFLECT_DURATION,
  SHADOW_DASH_COOLDOWN,
  SHEDIM_LMB_CAST,
  SHEDIM_RMB_CAST,
} from "./constants";
import type { ClassDef, SkillSlot } from "./types";

/**
 * Melee reach is a four-level ladder. Paragon's fists are level 1 (shortest),
 * Shedim's scythe level 2, Kacper's greatsword level 3.
 */
const FIST_RANGE = rangeFor(1);
const KATANA_RANGE = rangeFor(2);
const GREATSWORD_RANGE = rangeFor(3);

export const PARAGON: ClassDef = {
  id: "paragon",
  name: "Paragon",
  weapon: "Fists",
  blurb:
    "A bare-knuckle bruiser. Shorter reach than the katana, but his chains end in knockdowns and Combokiller turns a long string into a devastating finisher.",
  maxHp: 500,
  maxMana: 200,
  manaLabel: "Mana",
  manaPerHit: 5,
  // Raised from the original spec's 10: at 10, a basic hit landed for 6 after
  // armour and early fights dragged badly.
  attackPower: 25,
  attackRange: FIST_RANGE,
  rangeLevel: 1,
  baseArmor: 10,

  lmb: {
    id: "paragon-lmb",
    label: "Jab",
    kind: "lmb",
    castTime: PARAGON_LMB_CAST,
    activeAt: PARAGON_LMB_CAST * 0.45,
    activeDuration: 0.06,
    damageMult: 0.7,
    rangeMult: 1,
    height: 30,
    knockback: 2.2,
    effect: "none",
  },
  rmb: {
    id: "paragon-rmb",
    label: "Heavy Swing",
    kind: "rmb",
    castTime: PARAGON_RMB_CAST,
    activeAt: PARAGON_RMB_CAST * 0.55,
    activeDuration: 0.08,
    damageMult: 0.75,
    rangeMult: 1.05,
    height: 36,
    knockback: 4.5,
    effect: "none",
  },

  skills: [
    {
      slot: "Q",
      id: "reflect",
      label: "Reflect",
      kind: "skill",
      description:
        "Hold for 1 second. Any attack received during the stance is reflected back and throws the attacker into the air.",
      castTime: REFLECT_DURATION,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "launch",
      cooldown: REFLECT_COOLDOWN,
    },
    {
      slot: "E",
      id: "detonate",
      label: "Detonate",
      kind: "skill",
      description:
        "Overloads his own ki and erupts, blasting everything around him in every direction and hurling it away.",
      castTime: 0.45,
      activeAt: 0.26,
      activeDuration: 0.12,
      damageMult: 2.2,
      rangeMult: 2.6,
      height: 84,
      knockback: 16,
      effect: "knockdown",
      selfCentered: true,
      manaCost: 55,
      cooldown: 8,
    },
    {
      slot: "R",
      id: "armorbreak",
      label: "ArmorBreak",
      kind: "skill",
      description:
        "A very fast strike that shatters the opponent's guard, stripping their armour for 8 seconds.",
      castTime: 0.22,
      activeAt: 0.1,
      activeDuration: 0.07,
      damageMult: 1.0,
      rangeMult: 1.05,
      height: 34,
      knockback: 3,
      effect: "none",
      manaCost: 50,
      cooldown: ARMOR_BREAK_DURATION,
    },
    {
      slot: "F",
      id: "titan-slam",
      label: "Titan Slam",
      kind: "skill",
      description:
        "Slams the ground with both fists for 300% damage, knocking down everything nearby.",
      castTime: 0.6,
      activeAt: 0.38,
      activeDuration: 0.12,
      damageMult: 3.0,
      rangeMult: 2.1,
      height: 56,
      knockback: 10,
      effect: "knockdown",
      manaCost: 200,
      cooldown: 12,
    },
    {
      slot: "SHIFT",
      id: "iron-dash",
      label: "Iron Dash",
      kind: "skill",
      description:
        "A grounded burst forward with a short window of invulnerability. Unlike Shadow Dash it cannot pass through terrain.",
      castTime: PARAGON_DASH_TIME,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "none",
      cooldown: PARAGON_DASH_COOLDOWN,
    },
  ],

  // Taken from paragon.webp: masked, bare-chested, gold pauldron, ice crystal.
  colors: {
    primary: "#d49b7c",
    secondary: "#14131c",
    trim: "#e0b04a",
    skin: "#d49b7c",
    hair: "#2a1f1c",
    aura: "#95d9e4",
  },
};

export const SHEDIM: ClassDef = {
  id: "shedim",
  name: "Shedim",
  weapon: "Scythe",
  blurb:
    "A black-plate reaper with the longest reach in the game. Chains into air-launches and stuns, and phases through the map with Shadow Dash.",
  maxHp: 600,
  maxMana: 240,
  manaLabel: "Manapool",
  manaPerHit: 6,
  // Raised from 8, keeping the 1.25 : 1 ratio against Paragon.
  attackPower: 20,
  attackRange: KATANA_RANGE,
  rangeLevel: 2,
  baseArmor: 10,

  lmb: {
    id: "shedim-lmb",
    label: "Reap",
    kind: "lmb",
    castTime: SHEDIM_LMB_CAST,
    activeAt: SHEDIM_LMB_CAST * 0.45,
    activeDuration: 0.06,
    damageMult: 0.7,
    rangeMult: 1,
    height: 32,
    knockback: 2,
    effect: "none",
  },
  rmb: {
    id: "shedim-rmb",
    label: "Heavy Reap",
    kind: "rmb",
    castTime: SHEDIM_RMB_CAST,
    activeAt: SHEDIM_RMB_CAST * 0.55,
    activeDuration: 0.09,
    damageMult: 0.8,
    rangeMult: 1.08,
    height: 40,
    knockback: 4,
    effect: "none",
  },

  skills: [
    {
      slot: "Q",
      id: "shadow-slash",
      label: "Shadow Slash",
      kind: "skill",
      description:
        "Throws a crescent of shadow that travels forward and cuts through the air.",
      castTime: 0.28,
      activeAt: 0.14,
      activeDuration: 0.05,
      damageMult: 1.1,
      rangeMult: 1,
      height: 30,
      knockback: 3,
      effect: "none",
      manaCost: 30,
      cooldown: 3,
      invented: true,
    },
    {
      slot: "E",
      id: "crescent-rend",
      label: "Crescent Rend",
      kind: "skill",
      description: "A wide sweeping arc that carves everything in front of him.",
      castTime: 0.34,
      activeAt: 0.17,
      activeDuration: 0.1,
      damageMult: 1.4,
      rangeMult: 1.5,
      height: 48,
      knockback: 6,
      effect: "none",
      manaCost: 45,
      cooldown: 5,
      invented: true,
    },
    {
      slot: "R",
      id: "blade-flurry",
      label: "Blade Flurry",
      kind: "skill",
      description: "Three blindingly fast cuts delivered in a single motion.",
      castTime: 0.3,
      activeAt: 0.09,
      activeDuration: 0.18,
      damageMult: 0.6,
      rangeMult: 1.05,
      height: 36,
      knockback: 2,
      effect: "none",
      manaCost: 50,
      cooldown: 6,
      invented: true,
    },
    {
      slot: "F",
      id: "black-hole",
      label: "Black Hole",
      kind: "skill",
      description:
        "Tears open a singularity above himself that drags enemies toward him for 3 seconds.",
      castTime: 0.5,
      activeAt: 0.3,
      activeDuration: 0.05,
      damageMult: 0.5,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "none",
      manaCost: 200,
      cooldown: 14,
    },
    {
      slot: "SHIFT",
      id: "shadow-dash",
      label: "Shadow Dash",
      kind: "skill",
      description:
        "Dashes forward, immune to all damage for 1 second and passing straight through obstacles.",
      castTime: 0.3,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "none",
      cooldown: SHADOW_DASH_COOLDOWN,
    },
  ],

  // Taken from shaedim.webp: black plate, gold filigree, cyan scythe orb.
  colors: {
    primary: "#23222c",
    secondary: "#14141b",
    trim: "#c9a24a",
    skin: "#2b2a35",
    hair: "#101017",
    aura: "#3fe0e8",
  },
};

export const KACPER: ClassDef = {
  id: "kacper",
  name: "Kacper",
  weapon: "Greatsword",
  blurb:
    "A greatsword bruiser with level-3 reach. Every one of his strings converts into something: a charge that guards his front, an aerial slam, or a launcher. Bracing burns his own health in exchange for Stoic.",
  maxHp: 540,
  maxMana: 180,
  manaLabel: "Mana",
  manaPerHit: 6,
  attackPower: 14,
  attackRange: GREATSWORD_RANGE,
  rangeLevel: 3,
  baseArmor: 10,

  lmb: {
    id: "kacper-lmb",
    label: "Cleave",
    kind: "lmb",
    castTime: KACPER_LMB_CAST,
    activeAt: KACPER_LMB_CAST * 0.45,
    activeDuration: 0.07,
    damageMult: 1.0,
    rangeMult: 1,
    height: 40,
    knockback: 3,
    effect: "none",
  },
  rmb: {
    id: "kacper-rmb",
    label: "Heavy Cleave",
    kind: "rmb",
    castTime: KACPER_RMB_CAST,
    activeAt: KACPER_RMB_CAST * 0.55,
    activeDuration: 0.1,
    damageMult: 1.4,
    rangeMult: 1.08,
    height: 48,
    knockback: 6,
    effect: "none",
  },

  skills: [
    {
      slot: "Q",
      id: "kacper-guard",
      label: "Bulwark",
      kind: "skill",
      description:
        "Plants the greatsword and braces, gaining Stoic so incoming hits cannot interrupt him.",
      castTime: 0.6,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "none",
      manaCost: 30,
      cooldown: 7,
      invented: true,
    },
    {
      slot: "E",
      id: "kacper-sunder",
      label: "Sunder",
      kind: "skill",
      description: "An overhead chop that opens the target up and knocks them down.",
      castTime: 0.5,
      activeAt: 0.3,
      activeDuration: 0.1,
      damageMult: 2.0,
      rangeMult: 1.2,
      height: 54,
      knockback: 9,
      effect: "knockdown",
      manaCost: 45,
      cooldown: 8,
      invented: true,
    },
    {
      slot: "R",
      id: "kacper-uppercut",
      label: "Rising Edge",
      kind: "skill",
      description: "Swings upward, launching the target into the air.",
      castTime: 0.34,
      activeAt: 0.16,
      activeDuration: 0.09,
      damageMult: 1.5,
      rangeMult: 1.05,
      height: 58,
      knockback: 5,
      effect: "launch",
      effectDuration: 0.6,
      manaCost: 50,
      cooldown: 9,
      invented: true,
    },
    {
      slot: "F",
      id: "whirlwind",
      label: "Whirlwind",
      kind: "skill",
      description:
        "Spins with the greatsword for 4 seconds, carving everything around him. He can move freely, but cannot attack while it lasts.",
      castTime: KACPER_ULT_DURATION,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0.85,
      rangeMult: 1.6,
      height: 70,
      knockback: 5,
      effect: "none",
      selfCentered: true,
      manaCost: KACPER_ULT_COST,
      cooldown: KACPER_ULT_COOLDOWN,
    },
    {
      slot: "SHIFT",
      id: "kacper-dash",
      label: "Heavy Step",
      kind: "skill",
      description: "A short armoured lunge that shrugs off interruption.",
      castTime: 0.25,
      activeAt: 0,
      activeDuration: 0,
      damageMult: 0,
      rangeMult: 0,
      height: 0,
      knockback: 0,
      effect: "none",
      cooldown: 3.5,
      invented: true,
    },
  ],

  colors: {
    primary: "#5b6b8c",
    secondary: "#2b3245",
    trim: "#d8dee9",
    skin: "#d9a878",
    hair: "#6b4a2e",
    aura: "#ff6b4a",
  },
};

export const CLASSES: Record<string, ClassDef> = {
  paragon: PARAGON,
  shedim: SHEDIM,
  kacper: KACPER,
};

export function getClass(id: string): ClassDef {
  return CLASSES[id] ?? PARAGON;
}

export function skillOf(cls: ClassDef, slot: string) {
  return cls.skills.find((s) => s.slot === slot);
}

/**
 * The fifth skill slot is still called "SHIFT" internally (renaming the
 * SkillSlot union would ripple through engine.ts/ai.ts for no real benefit),
 * but the key actually bound to it moved off Shift entirely — holding Shift
 * while right-clicking is a browser-level escape hatch that ignores
 * preventDefault(), so every Dash-into-Heavy-Attack combo risked kicking the
 * native context menu open mid-fight. See input.ts's P1_BINDINGS. UI that
 * shows a skill's key hint should go through this rather than printing
 * `slot` directly.
 */
export function skillKeyLabel(slot: SkillSlot): string {
  return slot === "SHIFT" ? "C" : slot;
}
